version: "3.3"

networks:
  private:
   ipam:
      config:
      - subnet: 172.16.238.0/24

volumes:
  postgres:
  client:
  server:

services:
  redis:
    image: redis:latest
    networks:
      - private
    ports:
      - 6399:6379
    command: redis-server
  postgres:
    # TypeORM fails with Postgres v.12
    image: postgres:11.3
    ports:
      - 5455:5432
    env_file:
      - ../server/.env
    networks:
      - private
  
